name: map_history
description: A Map implementation with history and rollback support for entries, keys and values.
version: 1.0.4
homepage: https://github.com/gmpassos/map_history

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
   collection: ^1.18.0
   dependency_validator: ^4.1.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.9
